# ----------------------------------  CONTROLLER
# Authentication
controller_username: "{{ vault_controller_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
controller_password: "{{ vault_controller_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
controller_hostname: "{{ vault_controller_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
controller_validate_certs: "{{ vault_controller_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"

# Runtime Config
controller_configuration_users_secure_logging: false
controller_configuration_object_diff_secure_logging: false
controller_configuration_filetree_create_secure_logging: false

# ----------------------------------  FILETREE READ
# Controller Directory Path
filetree_controller_settings: "controller_config/settings.d/"
filetree_controller_organizations: "controller_config/organizations.d/"
filetree_controller_labels: "controller_config/labels.d/"
filetree_controller_user_accounts: "controller_config/users.d/"
filetree_controller_teams: "controller_config/teams.d/"
filetree_controller_credential_types: "controller_config/credential_types.d/"
filetree_controller_credentials: "controller_config/credentials.d/"
filetree_controller_credential_input_sources: "controller_config/credential_input_sources.d/"
filetree_controller_notifications: "controller_config/notification_templates.d/"
filetree_controller_projects: "controller_config/projects.d/"
filetree_controller_execution_environments: "controller_config/execution_environments.d/"
filetree_controller_applications: "controller_config/applications.d/"
filetree_controller_inventories: "controller_config/inventories.d/"
filetree_controller_inventory_sources: "controller_config/inventory_sources.d/"
filetree_controller_instance_groups: "controller_config/instance_groups.d/"
filetree_controller_hosts: "controller_config/hosts.d/"
filetree_controller_groups: "controller_config/groups.d/"
filetree_controller_templates: "controller_config/job_templates.d/"
filetree_controller_workflow_job_templates: "controller_config/workflow_job_templates.d/"
filetree_controller_schedules: "controller_config/schedules.d/"
filetree_controller_roles: "controller_config/roles.d/"
filetree_controller_instances: "controller_config/instances.d/"

# filetree_read tasks order and name
controller_configuration_filetree_read_tasks:
  - {name: settings, var: controller_settings, tags: settings}
  - {name: organizations, var: controller_organizations, tags: organizations}
  - {name: labels, var: controller_labels, tags: labels}
  - {name: user_accounts, var: controller_user_accounts, tags: users}
  - {name: teams, var: controller_teams, tags: teams}
  - {name: credential_types, var: controller_credential_types, tags: credential_types}
  - {name: credential_input_sources, var: controller_credential_input_sources, tags: credential_input_sources}
  - {name: credentials, var: controller_credentials, tags: credentials}
  - {name: notifications, var: controller_notifications, tags: notification_templates}
  - {name: projects, var: controller_projects, tags: projects}
  - {name: execution_environments, var: controller_execution_environments, tags: execution_environments}
  - {name: applications, var: controller_applications, tags: applications}
  - {name: inventories, var: controller_inventories, tags: inventories}
  - {name: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
  - {name: instance_groups, var: controller_instance_groups, tags: instance_groups}
  - {name: hosts, var: controller_hosts, tags: hosts}
  - {name: groups, var: controller_groups, tags: inventories}
  - {name: job_templates, var: controller_templates, tags: job_templates}
  - {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
  - {name: schedules, var: controller_schedules, tags: schedules}
  - {name: roles, var: controller_roles, tags: roles}

# ----------------------------------  OBJECT DIFF
controller_configuration_object_diff_tasks:
- {name: workflow_job_templates, var: controller_workflows, tags: workflow_job_templates}
- {name: job_templates, var: controller_templates, tags: job_templates}
- {name: roles, var: controller_roles, tags: roles}
- {name: teams, var: controller_teams, tags: teams}
- {name: user_accounts, var: controller_user_accounts, tags: users}
- {name: groups, var: controller_groups, tags: groups}
- {name: hosts, var: controller_hosts, tags: hosts}
- {name: inventory_sources, var: controller_inventory_sources, tags: inventory_sources}
- {name: inventories, var: controller_inventories, tags: inventories}
- {name: projects, var: controller_projects, tags: projects}
- {name: credentials, var: controller_credentials, tags: credentials}
- {name: credential_types, var: controller_credential_types, tags: credential_types}
- {name: organizations, var: controller_organizations, tags: organizations}
