# Documentation link : https://github.com/redhat-cop/controller_configuration/tree/devel/roles/hosts/README.md
# To use this resource copy paste the following code and modify the values :
---
controller_hosts:
  - name: localhost
    inventory: Network Inventory - IaC
    variables:
      some_var: some_val
      ansible_connection: local
