download_url: https://galaxy.ansible.com/download/redhat_cop-ah_configuration-1.1.1.tar.gz
format_version: 1.0.0
name: ah_configuration
namespace: redhat_cop
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.1.1
version_url: https://galaxy.ansible.com/api/v2/collections/redhat_cop/ah_configuration/versions/1.1.1/
